// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/zc-zht/super-job/admin/internal/repository"
	"github.com/zc-zht/super-job/admin/internal/repository/dao"
	"github.com/zc-zht/super-job/admin/internal/service"
	"github.com/zc-zht/super-job/admin/internal/web"
	"github.com/zc-zht/super-job/admin/ioc"
)

// Injectors from wire.go:

func InitWeb() *gin.Engine {
	db := ioc.InitDB()
	jobDAO := dao.NewJobDAO(db)
	jobRepository := repository.NewJobRepository(jobDAO)
	jobService := service.NewJobService(jobRepository)
	jobHandler := web.NewJobHandler(jobService)
	executorDAO := dao.NewExecutorDAO(db)
	executorRepository := repository.NewExecutorRepository(executorDAO)
	executorService := service.NewExecutorService(executorRepository)
	executorHandler := web.NewExecutorHandler(executorService)
	engine := ioc.InitWebServer(jobHandler, executorHandler)
	return engine
}
