// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/ac-zht/super-job/admin/internal/repository"
	"github.com/ac-zht/super-job/admin/internal/repository/dao"
	"github.com/ac-zht/super-job/admin/internal/service"
	"github.com/ac-zht/super-job/admin/internal/web"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWeb() *gin.Engine {
	db := InitTestDB()
	taskDAO := dao.NewTaskDAO(db)
	taskRepository := repository.NewTaskRepository(taskDAO)
	taskService := service.NewTaskService(taskRepository)
	taskHandler := web.NewTaskHandler(taskService)
	executorDAO := dao.NewExecutorDAO(db)
	executorRepository := repository.NewExecutorRepository(executorDAO)
	executorService := service.NewExecutorService(executorRepository)
	executorHandler := web.NewExecutorHandler(executorService)
	engine := InitTestWebServer(taskHandler, executorHandler)
	return engine
}

// wire.go:

var thirdProvider = wire.NewSet(
	InitTestDB,
)

var executorSvcProvider = wire.NewSet(dao.NewExecutorDAO, repository.NewExecutorRepository, service.NewExecutorService, web.NewExecutorHandler)

var taskSvcProvider = wire.NewSet(dao.NewTaskDAO, repository.NewTaskRepository, service.NewTaskService, web.NewTaskHandler)
