// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/zc-zht/super-job/admin/internal/repository"
	"github.com/zc-zht/super-job/admin/internal/repository/dao"
	"github.com/zc-zht/super-job/admin/internal/service"
	"github.com/zc-zht/super-job/admin/internal/web"
)

// Injectors from wire.go:

func InitWeb() *gin.Engine {
	db := InitTestDB()
	jobDAO := dao.NewJobDAO(db)
	jobRepository := repository.NewJobRepository(jobDAO)
	jobService := service.NewJobService(jobRepository)
	jobHandler := web.NewJobHandler(jobService)
	executorDAO := dao.NewExecutorDAO(db)
	executorRepository := repository.NewExecutorRepository(executorDAO)
	executorService := service.NewExecutorService(executorRepository)
	executorHandler := web.NewExecutorHandler(executorService)
	engine := InitTestWebServer(jobHandler, executorHandler)
	return engine
}

// wire.go:

var thirdProvider = wire.NewSet(
	InitTestDB,
)

var executorSvcProvider = wire.NewSet(dao.NewExecutorDAO, repository.NewExecutorRepository, service.NewExecutorService, web.NewExecutorHandler)

var jobSvcProvider = wire.NewSet(dao.NewJobDAO, repository.NewJobRepository, service.NewJobService, web.NewJobHandler)
